version: '3'

services:
  mapnik:
    build:
      context: geobacter/mapnik/
      dockerfile: Dockerfile
    image: mapnik
    volumes:
      - openstreetmap-data:/var/lib/postgresql/12/main
      - openstreetmap-rendered-tiles:/var/lib/mod_tile
    ports:
      - "8080:80"
      # Expose postgres database
      # - "5432:5432"
    environment:
      - THREADS=8
    command: "run"

volumes:
  openstreetmap-data:
    external: true
  openstreetmap-rendered-tiles:
    external: true